using Test
using ACTLikelihoods
using DelimitedFiles

# Canonical data location
const DATA_DIR = joinpath(@__DIR__, "..", "data", "ACT_DR6_CMB_only")
const REF_DIR  = joinpath(@__DIR__, "reference_cls")

function load_cls(filepath::String)
    data = readdlm(filepath)
    # The file has 2 columns: ell, Dl. We only want Dl.
    return Float64.(data[:, 2])
end

@testset "Numerical parity with candl Python" begin
    # 1. Initialize Julia likelihood
    like = ACTDR6Likelihood(DATA_DIR)
    
    # 2. Load the synthetic reference spectra generated by candl
    Dl_TT = load_cls(joinpath(REF_DIR, "Dl_TT.txt"))
    Dl_TE = load_cls(joinpath(REF_DIR, "Dl_TE.txt"))
    Dl_EE = load_cls(joinpath(REF_DIR, "Dl_EE.txt"))
    
    # 3. Evaluate Julia log-likelihood
    # A_act and P_act match the 1.0 used in the python script.
    params = (A_act=1.0, P_act=1.0)
    Dls_CMB = (TT=Dl_TT, TE=Dl_TE, EE=Dl_EE)
    
    julia_ll = loglike(like, params, Dls_CMB)
    
    # Load candl intermediate outputs
    ref_ll = Float64(readdlm(joinpath(REF_DIR, "candl_loglike.txt"))[1, 1])
    
    # 4. Compare
    println("candl log-like = ", ref_ll)
    println("Julia log-like = ", julia_ll)
    println("Difference     = ", abs(julia_ll - ref_ll))
    
    # We require precision up to 1e-8 relative
    @test isapprox(julia_ll, ref_ll, rtol=1e-8)
end
